services:
  postgres-dev:
    image: postgres:17.0
    container_name: podracing-postgres-dev
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: podracing-database-dev
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-pw

  postgres-test:
    image: postgres:17.0
    container_name: podracing-postgres-test
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: podracing-database-test
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pw